examples: 
	../adjsc -I .. -t test1 -o test1 test1.adjs
	../adjsc -I .. -t test2 -o test2 test2.adjs
	../adjsc -I .. -t test3 -o test3 test3.adjs
	../adjsc -I .. -t test4 -o test4 test4.adjs
	../adjsc -I .. -t test5 -o test5 test5.adjs
	../adjsc -I .. -t test6 -o test6 test6.adjs
	../adjsc -I .. -t test7 -o test7 test7.adjs
#	../adjsc -I .. -t test8 -o test8 test8.adjs
#	../adjsc -I .. -t test8 -o test8 test8-broken.adjs
#	../adjsc -I .. -t test9 -o test9 test9-broken.adjs

clean:
	rm *.html *.js

